# -*- coding: utf-8 -*-
"""UTILIZATION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b6bQLelSWwdBoHntxgi_Wa3m9omwMPFe
"""

!pip install pandas matplotlib

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("healthcare_dataset.csv")  # DATA FILE
df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])
df["Discharge Date"] = pd.to_datetime(df["Discharge Date"])
df["Length of Stay"] = (df["Discharge Date"] - df["Date of Admission"]).dt.days
df["Month"] = df["Date of Admission"].dt.to_period("M")

print("HOSPITAL VISITS")
print(f"Total visits: {len(df):,}")
print()
print("Visits by admission type:")
print(df["Admission Type"].value_counts())
print()

print("LENGTH OF STAY (days)")
print(f"Longest stay:  {df['Length of Stay'].max():.0f} days")
print(f"Shortest stay: {df['Length of Stay'].min():.0f} days")
print(f"Average stay:  {df['Length of Stay'].mean():.1f} days")
print(f"Median stay:   {df['Length of Stay'].median():.0f} days")
print()

print("MEDICAL CONDITIONS (Top 5)")
print(df["Medical Condition"].value_counts().head(5))
print()

print("MEDICATIONS (Top 5)")
print(df["Medication"].value_counts().head(5))
print()


print("ABNORMAL TEST RESULTS (For Chronic Care)")
abnormal = len(df[df["Test Results"] == "Abnormal"])
pct = (abnormal / len(df)) * 100
print(f"Total abnormal cases: {abnormal:,} ({pct:.1f}%)")
print()

print("BILLING ANALYSIS")
print(f"Highest bill: ${df['Billing Amount'].max():,.2f}")
print(f"Lowest bill:  ${df['Billing Amount'].min():,.2f}")
print(f"Average bill: ${df['Billing Amount'].mean():,.2f}")
print()


print("MONTHLY COST TRENDS")
monthly_costs = df.groupby("Month")["Billing Amount"].sum()
print(monthly_costs)

print("CHART")
monthly_costs.plot(kind="line", marker="o", figsize=(10, 6))
plt.title("Monthly Healthcare Costs")
plt.xlabel("Month")
plt.ylabel("Total Billing Amount ($)")
plt.grid(True, alpha=0.3)
plt.show()